language: scala

jdk:
  - oraclejdk8

script:
  - sbt headerCheck test docs/paradox

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

services:
  - docker

before_script:
  - sudo service postgresql stop # it's on by default
  - docker-compose up -d


