language: scala

jdk:
  - oraclejdk8

script:
  - sbt test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

services:
  - docker

before_script:
  - docker-compose up


