language: scala

jdk:
  - oraclejdk8

script:
  - sbt test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database world;' -U postgres
  - psql -c '\i world.sql' -d world -U postgres


